trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

variables:
  pythonVersion: '3.11'

jobs:
  - job: DeployResults
    displayName: 'Deploy Analysis Results'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(pythonVersion)'
          addToPath: true
        displayName: 'Setup Python'

      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        displayName: 'Install dependencies'

      - script: |
          echo "Publishing analysis results..."
        displayName: 'Deploy results'
